### ISSUE TITLE
Minify styles by selector

### ISSUE THREAD

**Issue by webschik** [jsFile/jsFile#10]
Now `JsFile` builds multiple style declaration with 1 selector:

``` css
.jf-page span, .jf-page p span {
    font-family: Times New Roman;
    font-size: 12pt;
}

.jf-page span, .jf-page p span {
    text-align: right;
}
```

It's better to group all these declarations to one by selector. Also maybe it makes sense to do it on the step of style creation (Create constructor like JsFile.Styles. It will do all optimization and build an HTML style structure). 
##
